#!/usr/bin/env python3
# ============================================================
# build_pages.py — Kabamo Digital v3 site generator
# Source of truth: _style.css + _script.js + the page bodies below.
# Edit those, then run:  python3 build_pages.py
# Do NOT hand-edit the generated *.html (they get overwritten).
#
# Pages:
#   index.html     — the coupled phone/process demonstrator + KPI teaser
#   dashboard.html — headline + scatter-dot region map + distribution/freshness/feed
#   manual.html    — how it works (content)
#   repo.html      — repository / usage (content)
# ============================================================
import pathlib

HERE = pathlib.Path(__file__).parent
CSS  = (HERE / "_style.css").read_text(encoding="utf-8")
JS   = (HERE / "_script.js").read_text(encoding="utf-8")

GH_REPO = "https://github.com/ursgehrig/kabamo-digital"

def nav(active):
    items = [("index.html","Demo"),("dashboard.html","Dashboard"),
             ("manual.html","How it works"),("repo.html","Repository")]
    links = "".join(
        f'<a href="{h}"{" class=\"active\"" if h==active else ""}>{t}</a>'
        for h,t in items)
    return ('<nav class="topnav"><div class="wrap">'
            '<span class="brand">Kabamo <span class="reg">Digital</span></span>'
            f'{links}</div></nav>')

FOOT = ('<div class="foot"><div class="wrap">'
        '<div>Kabamo Digital — USSD demand-register demonstrator · '
        f'Apache-2.0 · © 2026 Urs Gehrig · <a href="{GH_REPO}">GitHub</a></div>'
        '<div class="small">Method demonstrator, not a product. Synthetic / consented '
        'data only. Region views show counts, never real locations.</div>'
        '</div></div>')

def page(title, active, body):
    return f"""<!DOCTYPE html>
<!-- GENERATED by build_pages.py — do not hand-edit; edit _style.css / _script.js / the body in build_pages.py and rebuild. -->
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{title}</title>
<style>
{CSS}
</style>
</head>
<body>
{nav(active)}
{body}
{FOOT}
<script>
{JS}
</script>
</body>
</html>
"""

# ---------------------------------------------------------------- DEMO (index)
INDEX_BODY = """
<header class="page"><div class="wrap">
  <h1>Kabamo Digital — process demonstrator</h1>
  <p>Watch a health supply-chain process run, step by step. Choose a value chain, press Run, and follow which role is acting — the same flow that, underneath, runs on a basic phone via Unstructured Supplementary Service Data (USSD).</p>
  <p class="frozen">Group 3 result (presented) is frozen at <a href="../index.html">/kabamo/index.html</a>. This is the continued, enhanced version. New here? Start with <a href="manual.html">How it works</a>.</p>
</div></header>

<div class="wrap">

  <!-- value chains + process workflow -->
  <section>
    <div class="workflow">
      <p class="wftitle">Value chains</p>
      <p class="wfsub">Five processes across the end-to-end supply chain. Click a tile (or use the dropdown on the right) to select one.</p>
      <div class="cyclestrip" id="cycleStrip"></div>
      <p class="wftitle" style="margin-top:18px;">Process workflow</p>
      <p class="wfsub">The selected chain's ordered steps. The active step is highlighted as the process runs; completed steps turn green.</p>
      <div class="flowrow" id="flowRow"></div>
    </div>
  </section>

  <!-- duo: phone (left) + run controls (right) -->
  <section>
    <div class="duo">
      <div class="phonecol">
        <p class="coltitle">The phone <span class="sub">— the real USSD session <span class="dot" id="simDot"></span><span id="simTxt">behind each step</span></span></p>
        <div class="phone" id="simPhone">
          <div class="tag" id="simTag"></div>
          <div class="notch"></div>
          <div class="pscreen">
            <div class="ptitle" id="simScrTitle">Idle</div>
            <div class="pbody" id="simScrBody">Press Run process to start.</div>
            <div class="pdial" id="simDial"></div>
          </div>
          <div class="pad">
            <button onclick="KABAMO.simPress('1')">1</button><button onclick="KABAMO.simPress('2')">2</button><button onclick="KABAMO.simPress('3')">3</button>
            <button onclick="KABAMO.simPress('4')">4</button><button onclick="KABAMO.simPress('5')">5</button><button onclick="KABAMO.simPress('6')">6</button>
            <button onclick="KABAMO.simPress('7')">7</button><button onclick="KABAMO.simPress('8')">8</button><button onclick="KABAMO.simPress('9')">9</button>
            <button onclick="KABAMO.simPress('*')">*</button><button onclick="KABAMO.simPress('0')">0</button><button onclick="KABAMO.simPress('#')">#</button>
            <button class="back" onclick="KABAMO.simBack()" title="delete">&#9003;</button>
            <button class="call" onclick="KABAMO.simSend()" title="send">&#128222;</button>
          </div>
        </div>
        <p class="byhand">Or drive it by hand: <code>*</code> <code>3</code> <code>8</code> <code>4</code> <code>#</code> to dial, then digits. Role colour only — the menu is the same for everyone.</p>
        <div class="callerbox">
          <div class="callerline" id="callerLabel">no active caller</div>
          <button class="redial" onclick="KABAMO.redialSameHousehold()">&#8635; Same household re-dials</button>
          <div class="callerhint">New run = a new household (random number). Re-dial = the same household updates its record.</div>
        </div>
      </div>

      <div class="actcol">
        <p class="coltitle">Run the process <span class="sub">— choose, understand, then run</span></p>
        <div class="actsplit">
          <div class="left-acts">
            <div class="actstep">
              <label>&#9312; Choose the value chain</label>
              <select id="chainSel"></select>
            </div>
            <div class="infoblock">
              <span class="zlabel info">Information</span>
              <div class="chainctx" id="chainCtx"></div>
            </div>
            <div class="roleblock">
              <span class="zlabel role">Role in focus</span>
              <div class="rolectx" id="whoLine">&mdash;</div>
            </div>
          </div>
          <div class="right-acts">
            <div class="actstep">
              <label>&#9313; Run it</label>
              <div class="runbtns">
                <button id="runBtn" onclick="KABAMO.runnerNext()">Run process &#9656;</button>
                <button class="ghost" onclick="KABAMO.fullReset()">Reset</button>
              </div>
              <div class="narrate" id="runBox">
                <div class="nstep" id="rStep">Ready</div>
                <div class="nact" id="rAct">Pick a chain and press Run.</div>
              </div>
            </div>
          </div>
        </div>

        <!-- Live register sits under the two control columns, filling the space -->
        <div class="kpiteaser">
          <div class="kpihead">
            <span class="kt">Live register <span class="sub"><span class="dot" id="kpiDot"></span> <span id="kpiUpdated">checking…</span></span></span>
            <a class="kpilink" href="dashboard.html">See full dashboard &#8594;</a>
          </div>
          <div class="kpirow">
            <div class="kpi"><div class="k">Households</div><div class="v" id="k_hh">—</div><div class="s">registered</div></div>
            <div class="kpi"><div class="k">Sleeping spaces</div><div class="v" id="k_spaces">—</div><div class="s">net-demand units</div></div>
            <div class="kpi"><div class="k">Nets entitled</div><div class="v" id="k_nets">—</div><div class="s">capped 4/HH</div></div>
            <div class="kpi"><div class="k">Nets / person</div><div class="v" id="k_npp">—</div><div class="s">derived ratio</div></div>
          </div>
        </div>
      </div>
    </div>
  </section>

</div>
"""

# ------------------------------------------------------------------ DASHBOARD
DASHBOARD_BODY = """
<header class="page"><div class="wrap">
  <h1>Live register — dashboard</h1>
  <p>Anonymised aggregates from the demand register. No household is individually identifiable; small cells are suppressed (k-anonymity).</p>
</div></header>

<div class="wrap">
  <section>
    <div class="seedbanner" id="seedBanner"></div>
    <h2>Headline <span class="status-line"><span class="dot" id="liveDot"></span><span id="liveTxt">checking…</span></span></h2>
    <div class="cards" id="statCards">
      <div class="stat"><div class="k">Households</div><div class="v" id="s_hh">—</div><div class="s">registered</div></div>
      <div class="stat"><div class="k">Sleeping spaces</div><div class="v" id="s_spaces">—</div><div class="s">= net-demand units</div></div>
      <div class="stat"><div class="k">Nets entitled</div><div class="v" id="s_nets">—</div><div class="s">capped at 4/HH</div></div>
      <div class="stat"><div class="k">Nets / person</div><div class="v" id="s_npp">—</div><div class="s">derived ratio</div></div>
    </div>
  </section>

  <section>
    <h2>District coverage <span class="status-line">— who has reported for Chain 1</span></h2>
    <p class="lead">Reported vs. expected households per district. Under-reporting districts can be sent a reminder (simulated). Districts in red most need a nudge.</p>
    <div class="regiongrid" id="regionGrid"><p class="note">Loading…</p></div>
    <p class="rgcaption">Illustrative density only — dots are scattered at random within each district as a visual texture for the count. They are <b>not</b> individual household locations; no household position is stored or shown.</p>
    <div class="reminderlog" id="reminderLog"></div>
  </section>

  <section>
    <div class="row2">
      <div class="panel">
        <h3>Sleeping-space distribution</h3>
        <div id="distChart"><p class="note">Waiting for data…</p></div>
        <p class="note">Buckets with fewer than <b id="kanon">5</b> households are suppressed (k-anonymity).</p>
      </div>
      <div class="panel">
        <h3>Register freshness</h3>
        <div class="freshbar" id="freshBar"><div class="f" style="width:100%"></div></div>
        <p class="freshlabel" id="freshLabel">—</p>
        <h3 class="mt">Chain readiness <span class="status-line">(reports)</span></h3>
        <div id="chainList"><p class="note">No reports yet.</p></div>
        <h3 class="mt">Recent activity <span class="status-line">— anonymised, last 7</span></h3>
        <div id="recentFeed"><p class="note">No registrations yet.</p></div>
      </div>
    </div>
    <p class="note">Try the live demo on the <a href="index.html">Demo</a> page — registrations there appear here within ~15 seconds.</p>
  </section>
</div>
"""

# -------------------------------------------------------------------- MANUAL
MANUAL_BODY = """
<header class="page"><div class="wrap">
  <h1>How it works — and why</h1>
  <p>The problem the demonstrator addresses, the reframe it proposes, and what it is honest about.</p>
</div></header>

<div class="wrap"><div class="prose">

  <h2>The problem it addresses</h2>
  <p>Bed-net campaigns size demand from a stale census or a population estimate. The real unit of net demand is not headcount — it is <b>sleeping spaces (mattresses)</b>. Get the denominator wrong and you over- or under-supply, district by district. The supply chain assumes a live register of demand it rarely actually has.</p>

  <h2>The reframe: register the demand, keep it live</h2>
  <p>Make the household the reporter. A short USSD dialogue captures household size, under-5s, pregnancy and — crucially — sleeping spaces, derives a capped net entitlement, and timestamps the record for a ~6-month re-survey. This is a <i>consequent implementation</i> of the established sleeping-space (Senegal) method — not a claim of invention.</p>
  <div class="callout">Net demand is keyed on sleeping spaces, not people: the adult son on his own mattress is a real net need that a headcount-per-household rule would miss.</div>

  <h2>How the demo maps to a real process</h2>
  <p>The five value chains map onto the WHO/MSH management cycle:</p>
  <ul>
    <li><b>1 · Register the demand</b> → Selection &amp; Quantification (the flagship; builds the denominator)</li>
    <li><b>2 · Quantify &amp; allocate</b> → Selection &amp; Quantification</li>
    <li><b>3 · Supply to CHC</b> → Procurement</li>
    <li><b>4 · Last-mile &amp; resistance</b> → Storage &amp; Distribution</li>
    <li><b>5 · Protection &amp; monitoring</b> → Use (which loops back to refresh the register)</li>
  </ul>
  <p class="muted">The decomposition into five chains is a reasonable cut of the process, not a fact of the case.</p>

  <h2>USSD floor, smartphone ceiling</h2>
  <p>USSD is the <b>floor</b>: it works on any feature phone, with no app and no data plan, which is what reaches the unphoned-adjacent majority. A smartphone view over the same data model is the <b>ceiling</b> — richer entry where devices allow — never the minimum requirement.</p>

  <h2>The net cap is a budget control — not a demand truth</h2>
  <p>The 4-net household cap is a budget and equity control. At roughly 0.59 nets per person it sits about 18% over the one-net-per-two WHO target — a deliberate buffer. The sleeping-space count is the metric that balances budget, demand, vulnerability, region and transport. Monitoring should continuously challenge the cap rather than treat it as fixed truth.</p>

  <h2>New household vs. update — the demo</h2>
  <p>On the Demo page, each fresh run uses a new masked Tanzanian number, so distinct households accumulate. <b>Same household re-dials</b> reuses the last number, so the existing record updates (e.g. a pregnancy now reported) instead of creating a duplicate — demonstrating the continuous, re-surveyed register.</p>

  <h2>What we are honest about</h2>
  <div class="callout warn"><b>Coverage bias.</b> Phone self-report under-counts the unphoned poorest. Mitigation: CHW-assisted entry. USSD is the default channel, not the only one.</div>
  <div class="callout warn"><b>Data protection.</b> A household configuration against a (hashed) phone number is sensitive personal data. A real deployment needs a named data custodian, consent and purpose limitation (e.g. Tanzania PDPA 2022, GDPR-derived obligations). The demo uses synthetic / consented data only.</div>
  <div class="callout warn"><b>Not an outbreak tool.</b> This is for planned, recurring supply to a known population (ITNs, ORS/zinc, vitamin A, ARV/TB continuity, maternal-neonatal). Acute outbreak response is a different problem — deliberately excluded.</div>
  <div class="callout"><b>Reachability.</b> The sandbox code only works in the aggregator's web simulator. Real handsets need a paid live short code in a covered country (Tanzania: Vodacom/Airtel/Tigo — feasible). Not reachable on Swisscom (no aggregator interconnect).</div>

  <h2>Try it</h2>
  <p>Open the <a href="index.html">Demo</a>, pick a value chain, and press Run process — each step is a real exchange with the live <code>ussd.php</code>. Registrations show up on the <a href="dashboard.html">Dashboard</a> within about 15 seconds.</p>

</div></div>
"""

# --------------------------------------------------------------------- REPO
REPO_BODY = f"""
<header class="page"><div class="wrap">
  <h1>Repository &amp; usage</h1>
  <p>Open code, offered for reuse under Apache-2.0. The value is the method and its digitization; the code is open.</p>
</div></header>

<div class="wrap"><div class="prose">

  <h2>What's in the repository</h2>
  <table class="filetable">
    <thead><tr><th>File</th><th>Purpose</th></tr></thead>
    <tbody>
      <tr><td><code>ussd.php</code></td><td>USSD webhook (Africa's Talking contract: <code>sessionId</code>, <code>phoneNumber</code>, <code>text</code>; replies <code>CON …</code> / <code>END …</code>).</td></tr>
      <tr><td><code>dashboard.php</code></td><td>Read-only JSON aggregates. No row-level PII. k-anonymity suppression. Auto-seeds synthetic demo data when near-empty.</td></tr>
      <tr><td><code>seed.php</code></td><td>Creates the 6-district reference table and clearly-flagged synthetic demo households.</td></tr>
      <tr><td><code>schema.sql</code></td><td>SQLite schema (households / sessions / reports / chain_def + views).</td></tr>
      <tr><td><code>kabamo.db</code></td><td>Pre-built empty SQLite database (tables + views + chain definitions).</td></tr>
      <tr><td><code>index.html · dashboard.html · manual.html · repo.html</code></td><td>The generated site pages.</td></tr>
      <tr><td><code>build_pages.py · _style.css · _script.js</code></td><td>Site source — edit these, then rebuild the pages.</td></tr>
      <tr><td><code>test_local.php</code></td><td>Simulate USSD POSTs locally without an aggregator.</td></tr>
      <tr><td><code>README.md</code></td><td>Project overview, run instructions, and honest limitations.</td></tr>
      <tr><td><code>LICENSE</code></td><td>Full Apache License 2.0 text. Copyright © 2026 Urs Gehrig.</td></tr>
      <tr><td><code>NOTICE</code></td><td>Attribution notice required by the Apache license (Senegal-method credit; synthetic-data statement).</td></tr>
      <tr><td><code>.gitignore</code></td><td>Excludes runtime SQLite WAL sidecars and editor/OS cruft.</td></tr>
    </tbody>
  </table>
  <p class="muted">Every PHP source file also carries an Apache-2.0 licence header. The bundled <code>kabamo.db</code> ships empty; <code>seed.php</code> auto-populates clearly-flagged synthetic demo data on first view.</p>

  <h2>Use it in three steps</h2>

  <h3>1. Get the code</h3>
  <div class="btnrow"><a class="btn" href="{GH_REPO}">View on GitHub →</a></div>
  <p class="muted">Repository: <code>github.com/ursgehrig/kabamo-digital</code></p>

  <h3>2. Run it</h3>
  <pre><code>sqlite3 kabamo.db &lt; schema.sql   # or use the bundled kabamo.db
php -S localhost:8000 -t .       # serve this folder
# open http://localhost:8000/index.html</code></pre>
  <p>Test the endpoint exactly as an aggregator would:</p>
  <pre><code>curl -s -X POST http://localhost:8000/ussd.php \\
  -d 'sessionId=t1&amp;phoneNumber=+255700000001&amp;text=1*6*4*2*1'</code></pre>
  <p class="muted">The web user must have <b>write</b> permission on <code>kabamo.db</code> and its directory (SQLite WAL writes sidecar files).</p>

  <h3>3. Wire a USSD aggregator (for real phones)</h3>
  <p>Create an account with an aggregator that covers your target market (this prototype was tested against the Africa's Talking sandbox), point a USSD channel's callback at your deployed <code>ussd.php</code>, and walk the menu in the simulator. The sandbox short code works only in the simulator; real handsets need a live short code in a covered country — a deployment decision, not a prototype step.</p>

  <h2>Before any real deployment</h2>
  <ul>
    <li>Change <code>HASH_SALT</code> in <code>ussd.php</code> to a long random string. Phone numbers are stored sha256-hashed, never raw.</li>
    <li>Never commit a <code>kabamo.db</code> that holds real household data — only the empty one, or one with synthetic <code>seed=1</code> rows.</li>
    <li>Name a data custodian and secure consent + purpose limitation (Tanzania PDPA 2022, GDPR-derived obligations).</li>
  </ul>

  <div class="callout"><b>Editing the site.</b> The four HTML pages are generated by <code>build_pages.py</code> from <code>_style.css</code>, <code>_script.js</code> and the page bodies. Edit those sources, then run <code>python3 build_pages.py</code> — do not hand-edit the generated HTML.</div>

  <p class="muted">Licensed under Apache-2.0, © 2026 Urs Gehrig. Use, modify and redistribute — including commercially — provided you keep the copyright and license notices. Prototype / demonstrator: issues and forks welcome.</p>

</div></div>
"""

PAGES = {
    "index.html":     ("Kabamo Digital — demo",        "index.html",     INDEX_BODY),
    "dashboard.html": ("Kabamo Digital — dashboard",   "dashboard.html", DASHBOARD_BODY),
    "manual.html":    ("Kabamo Digital — how it works", "manual.html",   MANUAL_BODY),
    "repo.html":      ("Kabamo Digital — repository",  "repo.html",      REPO_BODY),
}

def main():
    out = HERE.parent  # write generated pages into v3/ (alongside src/)
    for fname,(title,active,body) in PAGES.items():
        html = page(title, active, body)
        (out / fname).write_text(html, encoding="utf-8")
        print(f"wrote {fname} ({len(html):,} bytes)")
    print("Done — 4 pages generated from _style.css + _script.js + bodies.")

if __name__ == "__main__":
    main()
